Enable overlayfs using raspi-config to protect rootfs from errors due to brownouts Disable AIY USB Gadget because it does not work with overlayfs Set swap file size to 0 since we are using tmpfs for overlay Set hostname during the first boot, remove ceti-tag-set-hostname systemd service

diff --git a/overlay/usr/lib/raspberrypi-sys-mods/firstboot b/overlay/usr/lib/raspberrypi-sys-mods/firstboot
--- a/overlay/usr/lib/raspberrypi-sys-mods/firstboot
+++ b/overlay/usr/lib/raspberrypi-sys-mods/firstboot
@@ -168,6 +168,40 @@ do_resize () {
   return "$RET"
 }
 
+sethostname() {
+  if [ -z "$NETWORK_ADAPTER_NAME" ]; then
+    NETWORK_ADAPTER_NAME="$(ls /sys/class/net/ | grep ^e | head -n1 | awk '{print $1;}')"
+  fi
+
+  MAC_ADDRESS="/sys/class/net/$NETWORK_ADAPTER_NAME/address"
+  if [ -f "$MAC_ADDRESS" ]; then
+	DEVICE_ID="$(< "$MAC_ADDRESS" sed s/':'//g)"
+  fi
+
+  if [ -z "$DEVICE_ID" ]; then
+	DEVICE_ID="$(< /proc/cpuinfo grep Serial | sed s/'.*:\s0*'/''/)"
+  fi
+
+  # If we still have no UID, just give up
+  if [ -z "$DEVICE_ID" ]; then
+    echo "Unable to find an identifier for the hw, exiting"
+    exit 1
+  fi
+
+  # Set device is as the hostname
+  DEVICE_ID="wt-$DEVICE_ID"
+  HOSTNAME="$(hostname)"
+
+  if [ "$HOSTNAME" != "$DEVICE_ID" ]; then
+    echo "Changing hostname to $DEVICE_ID"
+    hostname "$DEVICE_ID"
+    echo "127.0.0.1 $DEVICE_ID" >> /etc/hosts
+    echo "$DEVICE_ID" > /etc/hostname
+    sysctl kernel.hostname="$DEVICE_ID"
+  fi
+
+}
+
 regenerate_ssh_host_keys () {
   mount -o remount,rw /
   /usr/lib/raspberrypi-sys-mods/regenerate_ssh_host_keys
@@ -228,6 +262,8 @@ main () {
   fi
 
   fix_partuuid
+
+  sethostname
 
   raspi-config nonint do_ssh 0
 
